CANONICAL_COLUMNS = [
    "Person_Name",
    "Bank_Name",
    "Account_Number",
    "IFSC",
    "Statement_Start",
    "Statement_End",
    "Date",
    "Narration",
    "Chq_Ref",
    "Debit",
    "Credit",
    "Balance",
    "Merchant_Name",
    "Transaction_Mode",
    "Counterparty",
    "Category",
    "Sub_Category",
    "txn_seq",
    # Phase 0 — traceability
    "Transaction_ID",
    "Statement_File_Name",
    "Sheet_Name",
    "Statement_Row_No",
    "Financial_Year",
    # Phase 0 — confidence signal
    "Confidence",
    "Match_Reason",
    # Phase 0 — editable override columns (CA edits these)
    "Category_Final",
    "Sub_Category_Final",
    "GST_Flag",
    "Loan_Flag",
    "Tax_Flag",
    "CG_Flag",
    "Remarks",
]

CANONICAL_TYPES = {
    "Person_Name": str,
    "Bank_Name": str,
    "Account_Number": str,
    "IFSC": str,
    "Statement_Start": str,
    "Statement_End": str,
    "Narration": str,
    "Chq_Ref": str,
    "Debit": float,
    "Credit": float,
    "Balance": float,
    "Merchant_Name": str,
    "Transaction_Mode": str,
    "Counterparty": str,
    "Category": str,
    "Sub_Category": str,
    "txn_seq": int,
    # Phase 0 — traceability
    "Transaction_ID": str,
    "Statement_File_Name": str,
    "Sheet_Name": str,
    "Statement_Row_No": int,
    "Financial_Year": str,
    # Phase 0 — confidence signal
    "Confidence": str,
    "Match_Reason": str,
    # Phase 0 — editable override columns
    "Category_Final": str,
    "Sub_Category_Final": str,
    "GST_Flag": str,
    "Loan_Flag": str,
    "Tax_Flag": str,
    "CG_Flag": str,
    "Remarks": str,
}

# Columns that are locked (original evidence — CAs must not edit)
LOCKED_COLUMNS = [
    "Date",
    "Narration",
    "Debit",
    "Credit",
    "Balance",
    "Bank_Name",
    "Account_Number",
    "Transaction_ID",
    "Statement_File_Name",
    "Sheet_Name",
    "Statement_Row_No",
    "Financial_Year",
]

# Columns that are unlocked (CA-editable overrides)
UNLOCKED_COLUMNS = [
    "Category_Final",
    "Sub_Category_Final",
    "GST_Flag",
    "Loan_Flag",
    "Tax_Flag",
    "CG_Flag",
    "Remarks",
]
